<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ArticleSeeder extends Seeder
{
    private const WORDS_PER_MINUTE = 200;

    public function run(): void
    {
        $user = User::firstOrCreate(
            ['email' => 'admin@studilegalicatania.it'],
            [
                'name'     => 'Amministratore',
                'password' => Hash::make('password'),
            ]
        );

        $categories = Category::pluck('id', 'slug');

        $articles = [

            // ─── DIRITTO CIVILE ───────────────────────────────────────────
            [
                'category' => 'diritto-civile',
                'title'    => 'Risarcimento del danno: quando si ha diritto al rimborso',
                'body'     => '<p>Il risarcimento del danno costituisce uno dei pilastri del diritto civile italiano. L\'art. 2043 del Codice Civile stabilisce che "qualunque fatto doloso o colposo che cagiona ad altri un danno ingiusto obbliga colui che ha commesso il fatto a risarcire il danno". Per ottenere il risarcimento è necessario dimostrare quattro elementi fondamentali: il fatto illecito, il danno subito, il nesso causale tra il fatto e il danno, e la colpa o il dolo dell\'autore.</p><p>Il danno risarcibile si articola in diverse voci. Il danno patrimoniale comprende il danno emergente, ovvero le perdite economiche già subite, e il lucro cessante, cioè i mancati guadagni futuri. Il danno non patrimoniale include il danno biologico, il danno morale e il danno esistenziale, tutti riconosciuti dalla giurisprudenza della Corte di Cassazione come autonomamente risarcibili quando superano una soglia di gravità apprezzabile.</p><p>La procedura per ottenere il risarcimento parte generalmente da un tentativo di accordo stragiudiziale, inviando una lettera di messa in mora al responsabile o alla compagnia assicurativa. In assenza di risposta o in caso di offerta inadeguata, il danneggiato può ricorrere al giudice civile, presentando domanda di risarcimento con tutte le prove del danno subito. I termini di prescrizione variano in base alla natura del fatto illecito: in genere cinque anni per la responsabilità extracontrattuale, dieci anni per quella contrattuale.</p>',
                'months_ago' => 1,
            ],
            [
                'category' => 'diritto-civile',
                'title'    => 'Il contratto di locazione: obblighi di locatore e conduttore',
                'body'     => '<p>Il contratto di locazione ad uso abitativo è disciplinato principalmente dalla Legge 9 dicembre 1998, n. 431, che ha introdotto una regolamentazione più flessibile rispetto al passato, prevedendo due tipologie principali: i contratti a canone libero (4+4 anni) e i contratti a canone concordato (3+2 anni). Comprendere i reciproci obblighi è fondamentale per evitare controversie.</p><p>Il locatore ha l\'obbligo di consegnare l\'immobile in buono stato locativo e di mantenerlo in condizioni idonee all\'uso convenuto. È tenuto a eseguire le riparazioni straordinarie a proprie spese, a garantire il pacifico godimento dell\'immobile al conduttore e a restituire il deposito cauzionale entro i termini previsti dalla legge, aumentato degli interessi legali, salvo eventuali addebiti documentati. Il locatore non può unilateralmente modificare le condizioni contrattuali né accedere all\'immobile senza previo accordo con il conduttore.</p><p>Il conduttore, dal canto suo, deve corrispondere puntualmente il canone convenuto, osservare la destinazione d\'uso dell\'immobile, custodirlo con diligenza e restituirlo nelle medesime condizioni in cui è stato ricevuto, salvo il normale deterioramento. È tenuto a eseguire le piccole riparazioni derivanti dall\'uso ordinario e non può sublocare senza il consenso scritto del locatore. In caso di inadempimento grave, il locatore può agire per la risoluzione del contratto e lo sfratto per morosità, con procedura accelerata prevista dall\'art. 658 del Codice di Procedura Civile.</p>',
                'months_ago' => 2,
            ],
            [
                'category' => 'diritto-civile',
                'title'    => 'Successione ereditaria: come funziona la divisione dei beni',
                'body'     => '<p>La successione ereditaria si apre al momento della morte del de cuius e può avvenire per legge (successione legittima) o in base a un testamento (successione testamentaria). Il Codice Civile agli artt. 565 e seguenti stabilisce l\'ordine dei successibili nella successione legittima: in primo luogo il coniuge e i figli, poi i genitori e i fratelli, e così via. Quando coesistono più eredi si apre la comunione ereditaria, che si chiude con la divisione.</p><p>Un aspetto cruciale è la quota di legittima: la legge riserva ai legittimari (coniuge, figli, genitori) una quota minima dell\'eredità che il testatore non può privare. Se il testamento viola questa quota, i legittimari possono proporre l\'azione di riduzione per recuperare quanto loro spetta. La quota disponibile, ovvero la parte dell\'eredità di cui il testatore può liberamente disporre, varia in base al numero e alla tipologia dei legittimari presenti.</p><p>La divisione dell\'eredità tra più coeredi può avvenire consensualmente mediante accordo scritto tra le parti, con l\'assistenza di un notaio quando tra i beni vi sono immobili, oppure giudizialmente in caso di disaccordo. Nel corso della divisione si procede alla collazione, cioè al conteggio delle donazioni che il de cuius ha effettuato in vita ai discendenti, salvo espressa dispensa nel testamento. L\'accettazione dell\'eredità può avvenire in modo puro e semplice o con beneficio d\'inventario, quest\'ultima forma consigliabile quando si teme la presenza di debiti ereditari.</p>',
                'months_ago' => 3,
            ],
            [
                'category' => 'diritto-civile',
                'title'    => 'Responsabilità civile del professionista: limiti e tutele',
                'body'     => '<p>La responsabilità professionale è la responsabilità che grava sui professionisti intellettuali, quali avvocati, medici, ingegneri e commercialisti, per i danni causati ai propri clienti nell\'esercizio della professione. Si tratta di una responsabilità di natura contrattuale, disciplinata dall\'art. 1176 comma 2 del Codice Civile, che richiede al professionista la diligenza richiesta dalla natura dell\'attività esercitata e dalle specifiche competenze professionali.</p><p>La distinzione fondamentale è tra obbligazioni di mezzi e obbligazioni di risultato. Nelle obbligazioni di mezzi, tipiche della professione medica o forense, il professionista è tenuto ad impiegare ogni competenza e diligenza disponibile per perseguire l\'obiettivo del cliente, senza tuttavia garantirne il raggiungimento. Nelle obbligazioni di risultato, invece, il professionista risponde se il risultato pattuito non viene conseguito. La prova della colpa professionale spetta al cliente danneggiato, che deve dimostrare il nesso causale tra la condotta negligente e il danno subito.</p><p>Per tutelarsi, il cliente che ritiene di aver subito un danno per la negligenza di un professionista deve raccogliere tutta la documentazione disponibile, farla analizzare da un esperto di settore e procedere all\'invio di una diffida formale. In presenza di un danno significativo e documentato, è possibile attivare la polizza assicurativa obbligatoria del professionista o agire per via giudiziale entro i termini di prescrizione decennale previsti per la responsabilità contrattuale.</p>',
                'months_ago' => 4,
            ],
            [
                'category' => 'diritto-civile',
                'title'    => 'Inadempimento contrattuale: rimedi e tutele per il creditore',
                'body'     => '<p>L\'inadempimento contrattuale si verifica quando una delle parti non esegue la prestazione dovuta nei termini e con le modalità pattuite. L\'art. 1218 del Codice Civile stabilisce che il debitore inadempiente è tenuto al risarcimento del danno, a meno che non provi che l\'inadempimento è stato causato da impossibilità della prestazione derivante da causa a lui non imputabile. Il creditore insoddisfatto dispone di diversi strumenti di tutela.</p><p>Il rimedio principale è la risoluzione del contratto per inadempimento, disciplinata dagli artt. 1453 e seguenti del Codice Civile. Essa può essere giudiziale, quando il creditore chiede al giudice di pronunciarsi sulla risoluzione, oppure di diritto, quando il contratto prevede una clausola risolutiva espressa che opera automaticamente al verificarsi dell\'inadempimento. L\'eccezione di inadempimento (art. 1460 c.c.) consente alla parte creditrice di rifiutare la propria prestazione finché l\'altra parte non adempie, costituendo un potente strumento di tutela nelle more del giudizio.</p><p>Accanto alla risoluzione, il creditore può domandare l\'esecuzione forzata in forma specifica dell\'obbligazione, l\'azione di adempimento con contestuale risarcimento del danno, oppure far valere la penale contrattualmente pattuita, la quale ha la doppia funzione di predeterminare i danni e di rafforzare il vincolo contrattuale. Il concetto di messa in mora è fondamentale: prima di agire in giudizio è necessario intimare per iscritto al debitore di adempiere entro un termine congruo, costituendolo così formalmente in mora.</p>',
                'months_ago' => 5,
            ],

            // ─── DIRITTO PENALE ───────────────────────────────────────────
            [
                'category' => 'diritto-penale',
                'title'    => 'I diritti dell\'imputato: garanzie fondamentali nel processo penale',
                'body'     => '<p>Il processo penale italiano è costruito attorno al principio della presunzione di innocenza, sancito dall\'art. 27 della Costituzione: ogni persona accusata di un reato è considerata innocente fino a sentenza definitiva di condanna. A questo principio fondamentale si affiancano numerose garanzie processuali che assistono l\'indagato e l\'imputato in ogni fase del procedimento, a partire dal primo atto di indagine.</p><p>Tra i diritti primari vi è il diritto all\'assistenza difensiva: l\'indagato può scegliere liberamente il proprio difensore di fiducia oppure, se non in grado di provvedere, ha diritto a un difensore d\'ufficio nominato dal giudice. Il difensore ha accesso agli atti, può partecipare agli interrogatori, proporre eccezioni e produrre prove a discarico. Il diritto al silenzio garantisce che l\'imputato non sia obbligato a rispondere alle domande degli inquirenti: le sue dichiarazioni non possono mai essere usate contro di lui in sede di giudizio senza il suo consenso.</p><p>Il diritto al contraddittorio assicura che ogni prova a carico sia formata in udienza, alla presenza della difesa, consentendo l\'esame e il controesame dei testimoni. Il diritto all\'impugnazione permette di ricorrere contro le decisioni sfavorevoli attraverso i gradi di giudizio previsti dall\'ordinamento: appello avanti la Corte d\'Appello e ricorso per Cassazione per motivi di legittimità. La conoscenza di questi diritti è il primo passo per una difesa efficace.</p>',
                'months_ago' => 1,
            ],
            [
                'category' => 'diritto-penale',
                'title'    => 'Stalking e atti persecutori: come tutelarsi penalmente',
                'body'     => '<p>Il reato di atti persecutori, comunemente noto come stalking, è previsto dall\'art. 612-bis del Codice Penale, introdotto nel 2009 e successivamente modificato per rafforzare la tutela delle vittime. Il reato si configura quando una persona, con condotte reiterate, causa alla vittima un perdurante e grave stato di ansia o paura, un fondato timore per la propria incolumità o quella di persone vicine, oppure la costringono a modificare le proprie abitudini di vita.</p><p>La pena base è la reclusione da un anno a sei anni e sei mesi. La pena è aggravata se il fatto è commesso dal coniuge o partner, anche separato o divorziato, oppure con l\'uso di armi. Una delle misure più efficaci di protezione immediata è l\'ammonimento del questore: la vittima può rivolgersi direttamente alle forze dell\'ordine, che possono ammonire il persecutore invitandolo a cessare i comportamenti, con effetti rilevanti anche in caso di futuro processo. Parallelamente, la vittima può richiedere al giudice il divieto di avvicinamento ai luoghi frequentati, misura cautelare che può essere disposta anche in via d\'urgenza.</p><p>Per procedere penalmente è necessario presentare querela entro sei mesi dai fatti, salvo casi aggravati che procedono d\'ufficio. La vittima deve raccogliere tutte le prove possibili: messaggi, email, testimonianze, registrazioni, screenshot dei social network. L\'assistenza di un legale specializzato è fondamentale per orientarsi tra le misure di protezione disponibili e garantire la corretta raccolta della prova, spesso complessa in questi procedimenti.</p>',
                'months_ago' => 2,
            ],
            [
                'category' => 'diritto-penale',
                'title'    => 'Diffamazione online: responsabilità penale e tutela della reputazione',
                'body'     => '<p>La diffamazione è il reato previsto dall\'art. 595 del Codice Penale, che sanziona chiunque, comunicando con più persone, offende la reputazione di qualcuno. La forma aggravata disciplinata dal terzo comma prevede pene più severe quando il fatto è commesso con il mezzo della stampa o con qualsiasi altro mezzo di pubblicità. La giurisprudenza ha ormai consolidato l\'orientamento che include internet, i social network e i blog tra i mezzi di pubblicità ai fini dell\'aggravante.</p><p>La diffamazione online presenta caratteristiche peculiari rispetto a quella tradizionale. La potenziale viralità dei contenuti può causare un danno reputazionale molto più grave e immediato. I commenti offensivi pubblicati su Facebook, Instagram o nei forum possono raggiungere un numero indeterminato di persone in pochi minuti. La giurisprudenza ha chiarito che anche il semplice \'condivisione\' di un contenuto diffamatorio può integrare il reato, qualora il soggetto agisca con consapevolezza e dolo diffamatorio.</p><p>Per tutelarsi, la vittima deve in primo luogo documentare il contenuto offensivo mediante screenshot con data e ora ben visibili, prima che venga rimosso. Deve quindi presentare querela entro tre mesi dalla conoscenza del fatto, procedendo parallelamente all\'identificazione dell\'autore attraverso richiesta alle piattaforme. Accanto all\'azione penale, la vittima può richiedere il risarcimento del danno in sede civile, comprensivo del danno all\'immagine e del danno morale, anche mediante costituzione di parte civile nel processo penale.</p>',
                'months_ago' => 3,
            ],
            [
                'category' => 'diritto-penale',
                'title'    => 'Il patteggiamento: vantaggi, limiti e quando conviene',
                'body'     => '<p>Il patteggiamento, tecnicamente denominato "applicazione della pena su richiesta delle parti" e disciplinato dagli artt. 444-448 del Codice di Procedura Penale, è un rito alternativo al dibattimento che consente all\'imputato e al pubblico ministero di concordare una pena contenuta entro determinati limiti. Si tratta di uno strumento processuale di notevole rilevanza pratica, che offre significativi vantaggi in termini di riduzione della pena e di effetti accessori.</p><p>Il vantaggio principale del patteggiamento è la riduzione della pena fino a un terzo rispetto al minimo edittale per i reati ammissibili. Se la pena concordata non supera i due anni di reclusione, il giudice può applicare la sospensione condizionale della pena, evitando all\'imputato l\'espiazione effettiva. Ulteriori benefici consistono nella mancanza di condanna al pagamento delle spese processuali, nella non menzione della sentenza nel casellario giudiziale in caso di pena breve e nell\'estinzione del reato entro cinque anni (due per le contravvenzioni) se non si commettono nuovi reati.</p><p>Il patteggiamento non conviene in tutti i casi. L\'imputato che ritiene di essere innocente o comunque di avere buone possibilità assolutorie al dibattimento dovrebbe valutare attentamente questa scelta con il proprio difensore. Inoltre, la sentenza di patteggiamento produce effetti di giudicato nel processo civile per i danni derivanti dal reato. La decisione richiede un\'analisi approfondita degli atti, delle prove acquisite e della posizione processuale dell\'imputato, che solo un difensore di fiducia può condurre correttamente.</p>',
                'months_ago' => 4,
            ],
            [
                'category' => 'diritto-penale',
                'title'    => 'Detenzione domiciliare: requisiti e procedura per l\'istanza',
                'body'     => '<p>La detenzione domiciliare è una misura alternativa alla detenzione in carcere, disciplinata dall\'art. 47-ter dell\'Ordinamento Penitenziario (L. 354/1975), che consente all\'interessato di espiare la pena presso la propria abitazione o un altro luogo privato di dimora, ovvero presso una struttura di accoglienza. Rappresenta un importante strumento per il reinserimento sociale del condannato e per ridurre il sovraffollamento carcerario.</p><p>I requisiti soggettivi per l\'accesso alla detenzione domiciliare variano in base alla tipologia. La forma ordinaria è riservata a chi deve scontare una pena o un residuo di pena non superiore a quattro anni e quando ricorrono particolari condizioni soggettive, come la presenza di figli minori di dieci anni, gravi condizioni di salute o età avanzata. Esiste poi la detenzione domiciliare speciale per le madri o i padri con figli minori. Per i recidivi e per i condannati per reati ostativi, i requisiti sono più stringenti e l\'accesso è limitato o precluso.</p><p>L\'istanza va presentata al Tribunale di Sorveglianza competente corredata da documentazione completa: stato di famiglia, prova dell\'idoneità dell\'abitazione, certificazione medica se rilevante per la salute, progetto di trattamento e dichiarazione di disponibilità dell\'ente ospitante. Il Tribunale di Sorveglianza decide sentito il parere del Pubblico Ministero e, ove necessario, acquisita una relazione sull\'ambiente di vita. In caso di urgenza è possibile richiedere un provvedimento provvisorio al Magistrato di Sorveglianza.</p>',
                'months_ago' => 6,
            ],

            // ─── DIRITTO AMMINISTRATIVO ───────────────────────────────────
            [
                'category' => 'diritto-amministrativo',
                'title'    => 'Il ricorso al TAR: termini, presupposti e come presentarlo',
                'body'     => '<p>Il ricorso al Tribunale Amministrativo Regionale (TAR) è il principale strumento di tutela dei privati e delle imprese contro gli atti illegittimi della Pubblica Amministrazione. Disciplinato dal D.Lgs. 2 luglio 2010, n. 104 (Codice del Processo Amministrativo), il giudizio amministrativo consente di ottenere l\'annullamento degli atti viziati da incompetenza, eccesso di potere o violazione di legge, nonché il risarcimento del danno ingiusto subito.</p><p>Il termine generale per ricorrere al TAR è di sessanta giorni dalla piena conoscenza dell\'atto impugnato, termine perentorio la cui violazione determina l\'irricevibilità del ricorso. Nelle materie di giurisdizione esclusiva, come i provvedimenti in materia di pubblici contratti o di silenzio della PA, le regole processuali presentano alcune peculiarità. È fondamentale identificare con precisione il dies a quo del termine, cioè il momento dal quale decorrono i sessanta giorni: per gli atti notificati, è la data di ricezione della notifica; per quelli pubblicati all\'albo o in Gazzetta Ufficiale, la data di pubblicazione integrale.</p><p>Il ricorso deve contenere l\'indicazione del ricorrente e del resistente, la descrizione dell\'atto impugnato, i motivi di illegittimità (vizi di legittimità), le conclusioni e la procura al difensore. Contestualmente o con atto separato può essere chiesta la misura cautelare di sospensione dell\'efficacia dell\'atto impugnato, quando vi sia il periculum in mora, cioè il rischio che l\'esecuzione dell\'atto causi un danno grave e irreparabile nelle more del giudizio. L\'assistenza di un legale specializzato in diritto amministrativo è imprescindibile per la corretta redazione del ricorso e per l\'identificazione dei vizi rilevanti.</p>',
                'months_ago' => 2,
            ],
            [
                'category' => 'diritto-amministrativo',
                'title'    => 'L\'espropriazione per pubblica utilità: diritti e indennizzo del proprietario',
                'body'     => '<p>L\'espropriazione per pubblica utilità è il procedimento mediante il quale la Pubblica Amministrazione acquisisce la proprietà di un bene immobile privato per la realizzazione di opere di pubblica utilità, previo pagamento di un indennizzo al proprietario. Il testo unico in materia di espropriazioni per pubblica utilità è contenuto nel D.P.R. 8 giugno 2001, n. 327, che ha unificato e razionalizzato la disciplina precedentemente frammentata in numerose leggi speciali.</p><p>Il procedimento espropriativo si articola in diverse fasi. Prende avvio con la dichiarazione di pubblica utilità dell\'opera, contenuta nel progetto definitivo o nel piano urbanistico che la prevede. Segue la fase della determinazione dell\'indennità provvisoria, calcolata sulla base del valore venale del bene, e la sua offerta al proprietario. Se l\'indennità provvisoria viene accettata, il procedimento si conclude con il decreto di esproprio e il pagamento. Se invece il proprietario non accetta, l\'indennità viene determinata in via definitiva mediante una perizia e, in caso di persistente disaccordo, dalla Corte d\'Appello competente per territorio.</p><p>Il proprietario espropriato può opporsi al procedimento quando rilevi vizi di legittimità nell\'atto di dichiarazione di pubblica utilità, nel vincolo preordinato all\'esproprio o nel decreto di esproprio, presentando ricorso al TAR entro i termini ordinari. Può inoltre contestare la misura dell\'indennizzo ritenuta insufficiente, con azione avanti la Corte d\'Appello entro trenta giorni dall\'offerta definitiva. Il ricorso all\'occupazione d\'urgenza senza adeguato indennizzo può dar luogo a un\'azione risarcitoria per occupazione sine titulo.</p>',
                'months_ago' => 3,
            ],
            [
                'category' => 'diritto-amministrativo',
                'title'    => 'Appalti pubblici: tutela dell\'impresa esclusa e rimedi processuali',
                'body'     => '<p>Il settore degli appalti pubblici in Italia è regolato dal D.Lgs. 31 marzo 2023, n. 36, il nuovo Codice dei Contratti Pubblici, che ha recepito le direttive europee in materia. Quando un\'impresa ritiene di essere stata illegittimamente esclusa da una gara d\'appalto o di aver perso l\'aggiudicazione a causa di un\'irregolarità commessa dalla stazione appaltante, ha a disposizione strumenti di tutela sia in sede amministrativa che giurisdizionale.</p><p>Il rimedio principale è il ricorso al TAR competente entro trenta giorni dalla comunicazione dell\'esclusione o dell\'aggiudicazione definitiva all\'impresa ricorrente, termine ridotto rispetto a quello ordinario di sessanta giorni proprio per garantire la celerità del contenzioso in materia contrattuale. L\'impresa può chiedere contestualmente la sospensiva dell\'aggiudicazione, in modo da bloccare la stipula del contratto fino alla pronuncia del TAR nel merito. Se il contratto è già stato stipulato, il ricorrente può chiederne la dichiarazione di inefficacia, rimedio previsto dall\'art. 121 del Codice del Processo Amministrativo.</p><p>Accanto alla tutela demolitoria, ovvero l\'annullamento dell\'atto illegittimo, l\'impresa danneggiata può richiedere il risarcimento del danno per equivalente, che comprende il mancato utile d\'impresa (normalmente stimato al 10% del valore dell\'appalto) e i costi di partecipazione alla gara. La prova della lesione è semplificata dal meccanismo della "chance perduta": è sufficiente dimostrare la seria possibilità di aggiudicarsi l\'appalto in assenza dell\'atto illegittimo. La tempestività dell\'assistenza legale specializzata è determinante in questo ambito, stante la brevità dei termini processuali.</p>',
                'months_ago' => 4,
            ],
            [
                'category' => 'diritto-amministrativo',
                'title'    => 'Silenzio-inadempimento: come reagire all\'inerzia della Pubblica Amministrazione',
                'body'     => '<p>Il silenzio-inadempimento è la situazione che si verifica quando la Pubblica Amministrazione, obbligata per legge a provvedere entro un determinato termine su una domanda del privato, non lo fa. La legge n. 241 del 1990 fissa il termine generale di trenta giorni per la conclusione del procedimento amministrativo, salvo diversa previsione di legge o regolamento. Decorso inutilmente tale termine, il privato può agire avanti il giudice amministrativo per far dichiarare illegittimo il silenzio della PA e ottenere l\'ordine di provvedere.</p><p>Il ricorso avverso il silenzio è disciplinato dall\'art. 117 del Codice del Processo Amministrativo con un rito accelerato: il ricorso va depositato entro un anno dalla scadenza del termine di conclusione del procedimento e il giudice fissa l\'udienza entro trenta giorni dal deposito. Il giudice, accertata l\'illegittimità del silenzio, ordina alla PA di provvedere entro un termine stabilito, di norma trenta giorni. In caso di ulteriore inadempienza, nomina un commissario ad acta che si sostituisce all\'amministrazione nel compimento dell\'atto dovuto.</p><p>Occorre distinguere il silenzio-inadempimento, che costituisce comportamento illegittimo impugnabile, dal silenzio-assenso, meccanismo in cui la legge attribuisce valore positivo all\'inerzia della PA decorso un determinato periodo dalla presentazione dell\'istanza. Il silenzio-rigetto, invece, si configura in specifiche materie indicate dalla legge e consiste nel ritenere implicitamente rigettata la domanda al decorso del termine di conclusione del procedimento, aprendo così i termini per l\'impugnazione avanti il TAR. La distinzione tra queste forme di silenzio è giuridicamente rilevante e richiede una valutazione caso per caso.</p>',
                'months_ago' => 5,
            ],
            [
                'category' => 'diritto-amministrativo',
                'title'    => 'Accesso agli atti: il diritto del privato di ottenere i documenti della PA',
                'body'     => '<p>Il diritto di accesso ai documenti amministrativi è sancito dalla Legge 7 agosto 1990, n. 241, che ha introdotto nel nostro ordinamento il principio di trasparenza dell\'azione amministrativa. Il D.Lgs. 14 marzo 2013, n. 33, successivamente modificato dal D.Lgs. 97/2016, ha esteso ulteriormente il quadro normativo introducendo l\'accesso civico semplice e quello generalizzato (c.d. FOIA italiano), che consente a chiunque di accedere ai dati e ai documenti detenuti dalla PA senza dover dimostrare alcun interesse specifico.</p><p>L\'accesso documentale classico (art. 22 L. 241/1990) spetta ai soggetti privati che abbiano un interesse diretto, concreto e attuale a ottenere i documenti. La richiesta può essere presentata direttamente all\'ente detentore dei documenti, anche a mezzo PEC. La PA ha trenta giorni di tempo per rispondere: in caso di diniego espresso o di silenzio, il richiedente può presentare richiesta di riesame, ricorso al TAR entro trenta giorni o ricorso al Difensore Civico. Il diniego deve essere motivato, indicando le specifiche ragioni di esclusione contemplate dalla legge.</p><p>I limiti all\'accesso sono tassativamente previsti: tra di essi figurano i documenti coperti da segreto di Stato, quelli relativi a procedimenti tributari, le informazioni commerciali riservate, e i dati personali di terzi quando la loro divulgazione sia sproporzionata rispetto all\'interesse del richiedente. L\'accesso generalizzato invece è soggetto a limiti più ampi, finalizzati a bilanciare la trasparenza con la riservatezza. In ogni caso, l\'eventuale opposizione di terzi controinteressati deve essere valutata dall\'amministrazione prima di consentire l\'accesso ai relativi documenti.</p>',
                'months_ago' => 7,
            ],

            // ─── DIRITTO DEL LAVORO ───────────────────────────────────────
            [
                'category' => 'diritto-del-lavoro',
                'title'    => 'Licenziamento illegittimo: tutele reali e obbligatorie dopo il Jobs Act',
                'body'     => '<p>Il licenziamento è l\'atto unilaterale con cui il datore di lavoro risolve il rapporto di lavoro. Per essere legittimo deve essere sorretto da una causa prevista dalla legge: il giustificato motivo soggettivo (colpa grave del lavoratore), il giustificato motivo oggettivo (ragioni economiche o organizzative dell\'impresa) o la giusta causa (mancanza così grave da non consentire la prosecuzione anche provvisoria del rapporto). La distinzione è fondamentale perché le tutele applicabili variano significativamente.</p><p>Il D.Lgs. 23/2015 (Jobs Act) ha introdotto il regime delle "tutele crescenti" per i lavoratori assunti a tempo indeterminato dopo il 7 marzo 2015. In questo regime, il lavoratore licenziato illegittimamente ha generalmente diritto a un\'indennità risarcitoria (il cui importo varia in base all\'anzianità di servizio) e non alla reintegrazione nel posto di lavoro, salvo specifiche ipotesi. La reintegrazione è prevista nei casi più gravi: licenziamento discriminatorio, licenziamento disciplinare per fatto materialmente insussistente o licenziamento inefficace per vizi formali gravi.</p><p>Per i lavoratori assunti prima del 7 marzo 2015 che non rientrano nelle tutele crescenti, si applica ancora l\'art. 18 dello Statuto dei Lavoratori nella formulazione previgente al Jobs Act, che prevede la reintegra e il risarcimento in una gamma più ampia di ipotesi. In ogni caso, il lavoratore che intende impugnare il licenziamento deve farlo entro sessanta giorni dalla comunicazione, con qualsiasi atto scritto, anche stragiudiziale, e deve successivamente proporre il ricorso giudiziale entro 180 giorni. Il rispetto di questi termini decadenziali è essenziale per la conservazione di qualsiasi tutela.</p>',
                'months_ago' => 1,
            ],
            [
                'category' => 'diritto-del-lavoro',
                'title'    => 'Mobbing lavorativo: elementi costitutivi e azione legale',
                'body'     => '<p>Il mobbing è una condotta sistematica di vessazione psicologica posta in essere in ambito lavorativo, che può provenire dal datore di lavoro o da un superiore gerarchico (mobbing verticale) o dai colleghi di pari livello (mobbing orizzontale). Pur non essendo espressamente disciplinato da una norma di legge specifica nell\'ordinamento italiano, la sua risarcibilità è stata affermata dalla giurisprudenza della Corte di Cassazione sulla base degli artt. 2087 del Codice Civile e 32 della Costituzione, che tutelano la salute e la sicurezza del lavoratore.</p><p>Gli elementi costitutivi del mobbing individuati dalla giurisprudenza sono: la reiterazione nel tempo delle condotte ostili, la loro sistematicità e intenzionalità, l\'effetto lesivo sulla salute psicofisica del lavoratore e il nesso causale tra condotte e danno. La vittima deve documentare con precisione ogni singolo atto ostile, con date, orari e testimonianze. Sul piano probatorio, il lavoratore è tenuto a dimostrare il sistematico intento persecutorio, il che rende spesso necessario avvalersi di una perizia medico-legale che attesti il danno alla salute e il nesso con le condizioni lavorative.</p><p>Le azioni esperibili sono molteplici. In sede civile, il lavoratore può richiedere il risarcimento integrale del danno biologico, del danno morale e del danno professionale (perdita di chance di carriera), oltre a far valere la responsabilità del datore ex art. 2087 c.c. In sede penale, a seconda delle condotte specifiche, possono configurarsi i reati di lesioni personali, abuso d\'ufficio o violenza privata. L\'INAIL riconosce inoltre il danno da mobbing come malattia professionale, ammettendo la vittima alle relative tutele previdenziali.</p>',
                'months_ago' => 2,
            ],
            [
                'category' => 'diritto-del-lavoro',
                'title'    => 'Demansionamento: quando il mutamento di mansioni è illegittimo',
                'body'     => '<p>Il demansionamento consiste nell\'assegnazione del lavoratore a mansioni inferiori rispetto a quelle per cui è stato assunto o a quelle successivamente acquisite nel corso del rapporto di lavoro. La disciplina del mutamento di mansioni è contenuta nell\'art. 2103 del Codice Civile, significativamente modificato dal D.Lgs. 81/2015 (Jobs Act). La norma stabilisce in via generale la legittimità della mobilità orizzontale (a mansioni equivalenti) e introduce in via eccezionale la possibilità di assegnazione a mansioni inferiori.</p><p>L\'assegnazione unilaterale e definitiva a mansioni inferiori senza il consenso del lavoratore è illegittima, salvo nelle tassative ipotesi previste dalla legge: modifica degli assetti organizzativi aziendali con impatto sulla posizione del lavoratore, tutela della salute, accordo sindacale finalizzato al mantenimento dell\'occupazione. In questi casi il demansionamento è consentito con conservazione del precedente trattamento retributivo (tranne che per gli elementi strettamente connessi alle mansioni). Il lavoratore ha l\'obbligo di svolgere le nuove mansioni, ma può contemporaneamente agire in giudizio per la reintegra nel livello precedente e per il risarcimento del danno.</p><p>Il danno da demansionamento è plurimo: comprende il danno professionale, ovvero l\'impoverimento del bagaglio di competenze ed esperienze acquisite, il danno alla dignità e all\'immagine professionale e, nei casi più gravi accertati clinicamente, il danno biologico da stress. La prova del danno richiede una valutazione accurata delle mansioni precedentemente svolte, della loro rilevanza professionale e degli effetti concreti del mutamento sulla posizione del lavoratore. Il ricorso va presentato entro i termini di prescrizione ordinaria decennale, ma è fortemente consigliabile agire tempestivamente.</p>',
                'months_ago' => 4,
            ],
            [
                'category' => 'diritto-del-lavoro',
                'title'    => 'Infortuni sul lavoro: responsabilità del datore e risarcimento del danno',
                'body'     => '<p>L\'infortunio sul lavoro è l\'evento lesivo occorso al lavoratore in occasione di attività lavorativa, causato da una causa violenta ed esterna. Il sistema di tutela è fondato su un doppio binario: la tutela previdenziale dell\'INAIL (indennità, rendita) e la responsabilità civile e penale del datore di lavoro. L\'art. 2087 del Codice Civile sancisce l\'obbligo del datore di adottare nell\'esercizio dell\'impresa le misure che, secondo la particolarità del lavoro, l\'esperienza e la tecnica, sono necessarie a tutelare l\'integrità fisica e la personalità morale dei lavoratori.</p><p>L\'INAIL indennizza il lavoratore infortunato erogando prestazioni economiche proporzionali al grado di menomazione e alla retribuzione, nonché prestazioni sanitarie e riabilitative. Tuttavia, le prestazioni INAIL non coprono integralmente tutti i danni subiti dal lavoratore. Il danno differenziale è la differenza tra il risarcimento pieno spettante al lavoratore e quanto già riconosciuto dall\'INAIL: questo importo può essere richiesto al datore di lavoro in sede civile, dimostrando la sua responsabilità per la violazione degli obblighi di sicurezza.</p><p>Il datore di lavoro risponde anche penalmente quando l\'infortunio deriva da sua colpa o dolo: le fattispecie più ricorrenti sono le lesioni personali colpose e l\'omicidio colposo con violazione delle norme sulla prevenzione degli infortuni, puniti con pene significativamente aumentate rispetto all\'ipotesi base. Il lavoratore infortunato o i suoi familiari, in caso di decesso, devono agire tempestivamente denuncia INAIL entro due giorni dall\'infortunio, conservare tutti i referti medici e raccogliere prove dell\'ambiente di lavoro, avvalendosi di un legale specializzato per la valutazione complessiva del danno risarcibile.</p>',
                'months_ago' => 5,
            ],
            [
                'category' => 'diritto-del-lavoro',
                'title'    => 'Ferie non godute: diritti del lavoratore e monetizzazione',
                'body'     => '<p>Il diritto alle ferie è un diritto fondamentale del lavoratore, garantito dall\'art. 36 della Costituzione e dall\'art. 7 della Direttiva 2003/88/CE, recepita in Italia dal D.Lgs. 66/2003. Il lavoratore ha diritto a un periodo annuale di ferie retribuite non inferiore a quattro settimane, di cui almeno due settimane devono essere godute nel corso dell\'anno di maturazione. Il diritto alle ferie è irrinunciabile: qualsiasi accordo tra le parti che elimini o riduca questo diritto è nullo.</p><p>Il datore di lavoro ha la facoltà di fissare il periodo di fruizione delle ferie, tenendo conto delle esigenze dell\'impresa e degli interessi del lavoratore. Tuttavia, non può impedire sistematicamente la fruizione delle ferie. Se le ferie non sono state godute entro il 30 giugno dell\'anno successivo (salvo eccezioni), il datore di lavoro deve comunque assicurarne il godimento entro i diciotto mesi successivi al termine dell\'anno di maturazione, come stabilito dalla normativa europea. In caso di mancato godimento per cause imputabili al datore di lavoro, il lavoratore ha diritto al risarcimento del danno.</p><p>La monetizzazione delle ferie è vietata durante il rapporto di lavoro per le prime quattro settimane annuali (quota minima garantita dalla legge), mentre è possibile per le ferie eccedenti tale soglia e per quelle maturate e non godute all\'atto della cessazione del rapporto di lavoro. In quest\'ultimo caso, il datore di lavoro deve corrispondere l\'indennità sostitutiva delle ferie, calcolata sulla retribuzione giornaliera per ogni giorno di ferie non goduto. Il termine di prescrizione per le ferie maturate e non godute è di cinque anni dalla cessazione del rapporto di lavoro.</p>',
                'months_ago' => 8,
            ],
        ];

        foreach ($articles as $index => $data) {
            $categoryId = $categories[$data['category']];
            $publishedAt = now()->subMonths($data['months_ago'])->subDays(rand(0, 20));
            $wordCount   = str_word_count(strip_tags($data['body']));
            $readingTime = max(1, (int) ceil($wordCount / self::WORDS_PER_MINUTE));
            $slug        = Str::slug($data['title']);

            Article::updateOrCreate(
                ['slug' => $slug],
                [
                    'user_id'      => $user->id,
                    'category_id'  => $categoryId,
                    'title'        => $data['title'],
                    'slug'         => $slug,
                    'body'         => $data['body'],
                    'reading_time' => $readingTime,
                    'published_at' => $publishedAt,
                    'created_at'   => $publishedAt,
                    'updated_at'   => $publishedAt,
                ]
            );
        }
    }
}
